server:
  port: 8082                        #端口

spring:
  application:
    name: feign-service                                    #为服务命名

feign:
  hystrix:
    enabled: true                                        #一定要手动配置hystrix，默认feign是不开启hystrix服务的
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/


