server:
  port: 8082                        #端口

spring:
  application:
    name: feign-service                                    #为服务命名

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/           #指定开始的eureka server的注册中心
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/


